name: sentiment-analysis
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.9.15
  - pandas==1.5.2
  - scipy==1.9.3
  - bs4==4.11.1
  - requests==2.28.1
  - scikit-learn==1.1.3
  - nltk
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - transformers
  # Interactive
  - jupyter==1.0.0
  - matplotlib==3.6.2
  - seaborn==0.12.1
  # Testing
  - pycodestyle==2.10.0
  - pytest==7.2.0
  - pytest-cov==4.0.0
  - pytest-pycodestyle==2.3.1
  # Pip
  - pip==22.3.1
  - pip:
    - xgboost==1.6.2
